"""Board-derived agent performance ledger + chooser.

Builds a rolling 14-day view over the Kanban runs/events/comments the board
already carries, per (kind, provider, model), through the existing
``hermes_cli.kanban_db`` API - never raw SQL. The **served** model reported by
the completing run wins over the requested one when the two differ, so a
server-side route (Z.ai coding endpoint routing ``glm-5.1`` to ``glm-5.3``)
does not mislabel a row.

Task ``kind`` is opt-in: a card body may carry a ``kind:`` line whose value is
one of ``build|review|research|draft|ops``; anything else - including a
missing line - lands under ``unknown``. There is no keyword classifier.

``choose_agent(kind)`` returns a ``(provider, model)`` pair by review-pass
rate given >= 3 attempts; ties break by cheaper cost/attempt where a receipt
exists; if no data, callers fall back to static role routing. Every Nth
create for a kind (N=5, tunable) runs on the runner-up as a ``probe``. Ops
work is never probed.

M.4 router defaults (promote-on-evidence): ``load_defaults(path=None)``
reads the committed ``lessons/router_defaults.json`` (``{kind: {provider,
model, updated_at, evidence: {wins, losses, challenger}, pinned_until?}}``).
``choose_agent`` consults it FIRST for a kind; the Jarvis repo's
``soul/tools/router_promote.py`` writes it (apply_promotion after >= 3 net
shadow wins at <= cost; apply_pin after Harry thumbs-downs the digest line
for a 30-day pin).  Absent/corrupt file -> today's behaviour, byte-identical.

Lane M.1 scoreboard tier: ``load_scoreboard(path=None)`` reads the Jarvis
repo's per-card outcome scoreboard (``cards`` rows carrying card_id, kind,
outcome, model, provider, cost_usd, cost_status; window ``window_days``).
When the defaults entry for a kind is a 0-0 SEED it no longer
short-circuits: ``choose_agent`` ranks (provider, model) cells for the
kind by land rate (landed-or-review-passed / total, >= 3 cards), tie-break
cheaper mean cost over PRICED cards only (cost_status estimated/actual),
and returns reason ``scoreboard kind=<kind> <p>/<m> land=<0.00-1.00>
n=<cards> cost/landed=<usd or ?> window=<W>d``.  Missing/corrupt
scoreboard -> tier skipped, never raises, behaviour byte-identical to
today.  Default path is GRUNTY-local (Jarvis repo checkout on Harry's
Windows control host); ``HERMES_SCOREBOARD`` env overrides.
"""

from __future__ import annotations

import dataclasses
import json
import os
import re
import statistics
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence

from hermes_cli import kanban_db as kb
from hermes_cli import kanban_db_connect as kbc


# ---------------------------------------------------------------------------
# M.4 router defaults file (promote-on-evidence, slice c)
# ---------------------------------------------------------------------------
#
# The per-kind DEFAULT (provider, model) is not a static in this module and
# not config.yaml: it is one JSON file, COMMITTED data (defaults survive
# checkout; the runtime router ledger is ignored, the defaults file is
# truth).  Shape:
#
#     {"<kind>": {"provider": str, "model": str, "updated_at": iso,
#                 "evidence": {"wins": int, "losses": int,
#                              "challenger": "provider/model" | null,
#                              "incumbent": "provider/model" | null},
#                 "pinned_until": iso | omitted}}
#
# choose_agent reads it FIRST for a kind; delete the file -> today's
# behaviour (byte-identical fallback, proven in tests).  M.4 (the Jarvis
# repo's soul/tools/router_promote.py) is the only writer: apply_promotion
# after >= 3 net shadow wins at <= cost, apply_pin after Harry thumbs-downs
# the digest line (30-day pinned_until).  Pinned kinds are skipped by
# promotion, not by this chooser.
#
# Note (deviation, documented): the slice decision named the path
# ``hermes/lessons/router_defaults.json``.  In THIS repo the name ``hermes``
# is a tracked launcher file, so a ``hermes/lessons/`` directory cannot
# exist here; the committed file lives at ``<repo>/lessons/
# router_defaults.json``.  router_promote.write_defaults resolves the same
# location in the live checkout.

DEFAULTS_FILENAME = "router_defaults.json"

# Lane M.1: the Jarvis repo's per-card outcome scoreboard (land rates per
# (kind, provider, model), generated by hermes/tools/scoreboard.py).  The
# default path is GRUNTY-local (that repo lives only on Harry's Windows
# control host); everywhere else the file is absent and this tier is
# skipped, leaving behaviour byte-identical to today.  Env override:
# HERMES_SCOREBOARD=/abs/path/scoreboard.json (tests, other hosts).
DEFAULT_SCOREBOARD_PATH = Path(
    "C:/Users/User/DiscordBots/Jarvis/hermes/lessons/scoreboard.json"
)

# Scoreboard outcomes that count as "landed" for the chooser's land rate:
# the card's work landed (build/research/draft/ops) or the review passed
# (review kind) - mirrors scoreboard_query.query_kind_model's "landed".
LANDED_OUTCOMES = frozenset({"landed", "review-passed"})

# cost_status values meaning "this cost_usd is a real measurement" (never
# "unknown" - an unknown-cost provider must not fake a cheap average).
_PRICED_COST_STATUSES = frozenset({"estimated", "actual"})

# A (provider, model) cell needs at least this many cards in the window
# before it can win the kind (same bar as the ledger tier's min_attempts).
SCOREBOARD_MIN_CARDS = 3


def _defaults_path() -> Path:
    """The committed defaults file in this checkout (env-overridable for the
    M.4 loop and tests)."""
    env = os.environ.get("HERMES_ROUTER_DEFAULTS")
    if env:
        return Path(env)
    return Path(__file__).resolve().parent.parent / "lessons" / DEFAULTS_FILENAME


def load_scoreboard(path: Optional[str] = None) -> dict:
    """Read the Jarvis scoreboard (Lane M.1).

    Missing file / corrupt JSON / non-dict / no ``cards`` list all return
    ``{}`` (never raise) so the chooser's scoreboard tier is skipped and
    behaviour falls back to today's.  ``path`` overrides the default
    GRUNTY-local location; env ``HERMES_SCOREBOARD`` overrides the default
    (explicit ``path`` argument still wins, mirroring ``load_defaults``).
    """
    if path is not None:
        src = Path(path)
    else:
        env = os.environ.get("HERMES_SCOREBOARD")
        src = Path(env) if env else DEFAULT_SCOREBOARD_PATH
    try:
        text = src.read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return {}
    if not isinstance(data, dict) or not isinstance(data.get("cards"), list):
        return {}
    return data


def _scoreboard_path() -> Path:
    """The scoreboard file the tier reads (env-overridable, tests/probe)."""
    env = os.environ.get("HERMES_SCOREBOARD")
    return Path(env) if env else DEFAULT_SCOREBOARD_PATH


def _scoreboard_rank(
    data: dict, kind: str, assignee: Optional[str] = None,
) -> list[dict]:
    """Rank (provider, model) cells for ``kind`` from scoreboard ``cards``.

    Assignee slicing per the card: apply the assignee filter ONLY when an
    ``assignee`` was passed AND rows carry an ``assignee`` field AND >= 3
    rows survive; otherwise kind-only.  Returns ranked rows:
    land_rate desc, then cheaper mean cost_usd (priced cards only) asc,
    then provider/model for determinism.  Cells with < 3 cards are dropped.
    """
    rows = data.get("cards") or []
    use_assignee = False
    if assignee is not None:
        with_field = [r for r in rows if isinstance(r, dict) and "assignee" in r]
        if with_field:  # rows carry the field at all
            surviving = [r for r in with_field
                         if str(r.get("assignee") or "") == str(assignee)]
            if len(surviving) >= SCOREBOARD_MIN_CARDS:
                rows, use_assignee = surviving, True
    cells: dict[tuple[str, str], dict] = {}
    for r in rows:
        if not isinstance(r, dict):
            continue
        if str(r.get("kind") or "").lower() != kind:
            continue
        model, provider = r.get("model"), r.get("provider")
        if not model or not provider:
            continue  # gate-refused/crashed cards carry null model
        key = (str(provider).lower(), str(model))
        c = cells.setdefault(key, {
            "provider": str(provider).lower(), "model": str(model),
            "cards": 0, "landed": 0, "cost_sum": 0.0, "cost_n": 0,
        })
        c["cards"] += 1
        if str(r.get("outcome") or "") in LANDED_OUTCOMES:
            c["landed"] += 1
        if r.get("cost_status") in _PRICED_COST_STATUSES:
            try:
                c["cost_sum"] += float(r.get("cost_usd") or 0.0)
                c["cost_n"] += 1
            except (TypeError, ValueError):
                pass
    ranked = [c for c in cells.values() if c["cards"] >= SCOREBOARD_MIN_CARDS]
    for c in ranked:
        c["land_rate"] = c["landed"] / c["cards"]
        c["mean_cost"] = (c["cost_sum"] / c["cost_n"]) if c["cost_n"] else None
    ranked.sort(key=lambda c: (-c["land_rate"], c["mean_cost"] if c["mean_cost"] is not None else float("inf"), c["provider"], c["model"]))
    for c in ranked:
        c["assignee_sliced"] = use_assignee
    return ranked


def _scoreboard_reason(kind: str, cell: dict, window_days: Any) -> str:
    """The chooser's one-line reason citing the scoreboard numbers it saw.

    ``cost/landed`` is spend per LANDED card (Lane M's goal metric): the
    sum of cost_usd over PRICED cards only, divided by landed cards.  "?"
    when the cell has no priced cards or nothing landed.
    """
    w = window_days if isinstance(window_days, int) else "?"
    if cell["cost_n"] > 0 and cell["landed"] > 0:
        cost = f"{cell['cost_sum'] / cell['landed']:.4f}"
    else:
        cost = "?"
    return (f"scoreboard kind={kind} {cell['provider']}/{cell['model']} "
            f"land={cell['land_rate']:.2f} n={cell['cards']} "
            f"cost/landed={cost} window={w}d")


def load_defaults(path: Optional[str] = None) -> dict:
    """Read the M.4 router defaults file.

    Missing / corrupt JSON / non-dict all return ``{}`` (never raise) so the
    chooser falls back to today's behaviour.  ``path`` overrides the default
    location (tests, and the M.4 promote loop writes the live copy).
    """
    src = Path(path) if path else _defaults_path()
    try:
        text = src.read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}



LEDGER_WINDOW_DAYS = 14
DEFAULT_PROBE_EVERY_N = 5
_KINDS = ("build", "review", "research", "draft", "ops", "unknown")
_KIND_LINE = re.compile(r"^\s*kind:\s*([A-Za-z_-]+)\s*$", re.MULTILINE)


def extract_kind(body: Optional[str]) -> str:
    """Return the ``kind:`` value declared in a card body (build|review|
    research|draft|ops), else ``unknown``. Missing body -> unknown. Never
    guesses from title/keywords."""
    if not body:
        return "unknown"
    m = _KIND_LINE.search(body)
    if not m:
        return "unknown"
    val = m.group(1).lower()
    return val if val in _KINDS else "unknown"


def _served_provider_model(run: kb.Run, task: kb.Task) -> tuple[Optional[str], Optional[str]]:
    """The (provider, model) the ledger should credit. Prefers what the model
    actually served (from the run's metadata / summary) over what was
    requested via ``tasks.model_override``/``provider_override``."""
    md = run.metadata or {}
    # Look for the receipt shape used elsewhere (see t_5eb9182a handoff).
    served_model = (md.get("model") or md.get("served_model") or md.get("model_reported")
                    or md.get("resolved_model"))
    served_provider = md.get("provider") or md.get("served_provider") or md.get("resolved_provider")
    # A worker's kanban_complete metadata may also carry a nested receipt.
    receipts = md.get("receipts") or []
    if isinstance(receipts, list) and receipts:
        last = receipts[-1] if isinstance(receipts[-1], dict) else {}
        served_model = served_model or last.get("model")
        served_provider = served_provider or last.get("provider")
    model = served_model or task.model_override
    provider = served_provider or task.provider_override
    return (str(provider).lower() if provider else None,
            str(model) if model else None)


def _reviewer_verdict(conn, child_id: str) -> Optional[str]:
    """A reviewer child's verdict for the ledger's review-pass column:
    ``pass`` (child status=done and no changes_requested outcome on any run),
    ``fail`` (had a changes_requested outcome), or ``None`` (still open)."""
    t = kb.get_task(conn, child_id)
    if t is None:
        return None
    # Anything with a changes_requested run counts as "fail" (rework).
    for r in kb.list_runs(conn, child_id, include_active=True):
        if r.outcome == "changes_requested":
            return "fail"
    if t.status == "done":
        return "pass"
    return None


@dataclass
class LedgerCell:
    kind: str
    provider: str
    model: str
    attempts: int = 0
    completed: int = 0
    review_pass: int = 0
    review_fail: int = 0
    blocked_needs_input: int = 0
    durations_s: list[int] = field(default_factory=list)
    tokens_in: int = 0
    tokens_out: int = 0
    cost_usd: float = 0.0
    cost_samples: int = 0

    def as_row(self) -> dict[str, Any]:
        med = int(statistics.median(self.durations_s)) if self.durations_s else None
        review_total = self.review_pass + self.review_fail
        return {
            "kind": self.kind,
            "provider": self.provider,
            "model": self.model,
            "attempts": self.attempts,
            "completed": self.completed,
            "review_pass": self.review_pass,
            "review_fail": self.review_fail,
            "review_pass_rate": (self.review_pass / review_total) if review_total else None,
            "blocked_needs_input": self.blocked_needs_input,
            "median_duration_s": med,
            "tokens_in": self.tokens_in or None,
            "tokens_out": self.tokens_out or None,
            "cost_usd": round(self.cost_usd, 6) if self.cost_usd else None,
            "cost_per_attempt": (
                round(self.cost_usd / self.attempts, 6) if self.cost_usd and self.attempts else None
            ),
        }


def _harvest_receipt(md: dict) -> tuple[int, int, float]:
    """Return (tokens_in, tokens_out, cost_usd) from a run metadata dict."""
    tin = int(md.get("tokens_in") or md.get("in") or md.get("input_tokens") or 0)
    tout = int(md.get("tokens_out") or md.get("out") or md.get("output_tokens") or 0)
    cost = float(md.get("cost_usd") or md.get("cost") or 0.0)
    receipts = md.get("receipts") or []
    if isinstance(receipts, list):
        for r in receipts:
            if not isinstance(r, dict):
                continue
            tin += int(r.get("in") or r.get("tokens_in") or r.get("input_tokens") or 0)
            tout += int(r.get("out") or r.get("tokens_out") or r.get("output_tokens") or 0)
            cost += float(r.get("cost_usd") or r.get("cost") or 0.0)
    return tin, tout, cost


def _latest_block_reason_is_needs_input(conn, task_id: str) -> bool:
    for ev in reversed(kb.list_events(conn, task_id)):
        if ev.kind == "blocked":
            payload = ev.payload or {}
            return str(payload.get("kind") or "").lower() == "needs_input"
    return False


def build_ledger(
    conn=None, *, now: Optional[int] = None,
    window_days: int = LEDGER_WINDOW_DAYS,
) -> dict[str, Any]:
    """Compute the ledger from the current board. Returns
    ``{"window_days": N, "generated_at": ts, "rows": [cell, ...],
       "totals": {"attempts": ..., "runs_considered": ...}}``.

    Caller may pass an already-open connection (tests); otherwise the
    module opens the active board itself.
    """
    def _run(_conn):
        now_ts = now if now is not None else int(time.time())
        cutoff = now_ts - window_days * 86400
        cells: dict[tuple[str, str, str], LedgerCell] = {}
        runs_considered = 0

        tasks = kb.list_tasks(_conn, include_archived=False)
        task_by_id = {t.id: t for t in tasks}
        for task in tasks:
            kind = extract_kind(task.body)
            runs = kb.list_runs(_conn, task.id, include_active=True)
            for run in runs:
                # Roll-off by start time; a run outside the window is skipped.
                if run.started_at < cutoff:
                    continue
                prov, model = _served_provider_model(run, task)
                if not prov or not model:
                    continue
                key = (kind, prov, model)
                cell = cells.setdefault(key, LedgerCell(kind=kind, provider=prov, model=model))
                cell.attempts += 1
                runs_considered += 1
                if run.outcome == "completed":
                    cell.completed += 1
                if run.ended_at:
                    cell.durations_s.append(int(run.ended_at - run.started_at))
                if run.metadata:
                    tin, tout, cost = _harvest_receipt(run.metadata)
                    cell.tokens_in += tin
                    cell.tokens_out += tout
                    if cost > 0:
                        cell.cost_usd += cost
                        cell.cost_samples += 1
            # Task-level accounting: needs-input blocks and reviewer verdicts.
            if task.status == "blocked" and _latest_block_reason_is_needs_input(_conn, task.id):
                # Credit the LAST run's cell (if any) with the needs-input strike.
                if runs:
                    r = runs[-1]
                    prov, model = _served_provider_model(r, task)
                    if prov and model:
                        cells.setdefault((kind, prov, model),
                                         LedgerCell(kind=kind, provider=prov, model=model)
                                         ).blocked_needs_input += 1
            # Reviewer-pass: this task's reviewer CHILDREN feed back into the
            # PARENT's cell (the parent is the card whose work was reviewed).
            child_ids = kb.child_ids(_conn, task.id)
            for cid in child_ids:
                child = task_by_id.get(cid)
                if child is None or extract_kind(child.body) != "review":
                    continue
                verdict = _reviewer_verdict(_conn, cid)
                if verdict is None:
                    continue
                # Attribute to the most recent completed run of the parent.
                last_run = None
                for r in reversed(runs):
                    if r.outcome == "completed":
                        last_run = r
                        break
                if last_run is None:
                    continue
                prov, model = _served_provider_model(last_run, task)
                if not prov or not model:
                    continue
                cell = cells.setdefault((kind, prov, model),
                                        LedgerCell(kind=kind, provider=prov, model=model))
                if verdict == "pass":
                    cell.review_pass += 1
                else:
                    cell.review_fail += 1
        rows = sorted(
            (c.as_row() for c in cells.values()),
            key=lambda r: (r["kind"], -(r["attempts"] or 0), r["provider"], r["model"]),
        )
        return {
            "window_days": window_days,
            "generated_at": now_ts,
            "rows": rows,
            "totals": {"attempts": sum(c.attempts for c in cells.values()),
                       "runs_considered": runs_considered,
                       "tasks_considered": len(tasks)},
        }

    if conn is not None:
        return _run(conn)
    with kbc.connect_closing() as _c:
        return _run(_c)


# --- Chooser -----------------------------------------------------------------

# Static routing when we have no signal (matches t_5eb9182a's role table).
_STATIC_ROLES: dict[str, tuple[str, str]] = {
    # 2026-09-24: workers run on API, never Harry's Claude subscription
    # (Jarvis roadmap rule 20). GLM-5.1 is the live default on both machines.
    "build": ("zai", "glm-5.1"),
    "review": ("zai", "glm-5.1"),
    "research": ("zai", "glm-5.1"),
    "draft": ("zai", "glm-5.1"),
    "ops": ("zai", "glm-5.1"),
    "unknown": ("zai", "glm-5.1"),
}


@dataclass
class ChooseResult:
    provider: str
    model: str
    reason: str            # "ledger" | "probe" | "static-no-data" | "static-ops-probe-refused"
    probe: bool = False
    runner_up: Optional[tuple[str, str]] = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "provider": self.provider,
            "model": self.model,
            "reason": self.reason,
            "probe": self.probe,
            "runner_up": list(self.runner_up) if self.runner_up else None,
        }


def _rank_for_kind(ledger: dict[str, Any], kind: str, *, min_attempts: int = 3):
    """Return ``[(cell_row, ...), ...]`` for this kind, ordered by review pass
    rate desc then cheaper cost-per-attempt asc (ties). Only cells with at
    least ``min_attempts`` attempts are considered."""
    contenders = [
        r for r in ledger["rows"]
        if r["kind"] == kind and r["attempts"] >= min_attempts and r["review_pass_rate"] is not None
    ]

    def key(r):
        cpa = r["cost_per_attempt"] if r["cost_per_attempt"] is not None else float("inf")
        return (-r["review_pass_rate"], cpa, r["provider"], r["model"])
    return sorted(contenders, key=key)


def _count_cards_of_kind(conn, kind: str) -> int:
    """Cards created (any disposition) whose body declares this ``kind``.

    Used for the every-Nth probe cadence, which is create-indexed.  Cheap:
    bodies only, no runs/events scan.  Best-effort - 0 on any error.
    """
    try:
        rows = conn.execute("SELECT body FROM tasks").fetchall()
    except Exception:
        return 0
    n = 0
    for row in rows:
        body = row[0] if not hasattr(row, "keys") else row["body"]
        if extract_kind(body) == kind:
            n += 1
    return n


def choose_agent(
    kind: str,
    *,
    ledger: Optional[dict[str, Any]] = None,
    cards_of_kind_created_so_far: int = 0,
    probe_every_n: int = DEFAULT_PROBE_EVERY_N,
    conn=None,
    assignee: Optional[str] = None,
    scoreboard: Optional[dict] = None,
) -> ChooseResult:
    """Pick (provider, model) for a card of this ``kind``.

    - The M.4 defaults file (``load_defaults``) is consulted FIRST.  An
      entry with real evidence (wins+losses >= 1) wins outright, reason
      citing the promotion evidence numbers (``3-1 vs ...``).
    - A defaults entry that is still a SEED (wins+losses == 0) does NOT
      short-circuit: it defers to the scoreboard tier (Lane M.1), which
      ranks (provider, model) cells for the kind from the Jarvis
      scoreboard's window by land rate (>= 3 cards), tie-break cheaper
      mean cost over priced cards only.  Missing/corrupt scoreboard ->
      fall through to the ledger tier, behaviour byte-identical to today.
    - ``assignee`` (optional) narrows scoreboard rows when they carry an
      ``assignee`` field and >= 3 survive; otherwise kind-only.
    - Best review-pass rate at >= 3 attempts wins; ties -> cheaper.
    - Every Nth card of a kind (``cards_of_kind_created_so_far % N == 0``)
      runs on the runner-up as a ``probe`` (never for ops).
    - Zero signal -> static role routing.
    """
    kind = kind if kind in _KINDS else "unknown"

    # M.4 defaults file wins first (absent/corrupt -> today's behaviour).
    entry = load_defaults().get(kind)
    defaults_is_seed = True
    if isinstance(entry, dict) and entry.get("provider") and entry.get("model"):
        ev = entry.get("evidence") or {}
        wins = ev.get("wins", 0)
        losses = ev.get("losses", 0)
        challenger = ev.get("challenger") or ev.get("incumbent") or "seed"
        if (wins or 0) + (losses or 0) >= 1:
            # Promote-on-evidence beats reactive (binding precedence (a)).
            reason = f"defaults-file {wins}-{losses} vs {challenger}"
            return ChooseResult(entry["provider"], entry["model"], reason=reason)
        defaults_is_seed = True
    else:
        defaults_is_seed = False  # no usable entry at all

    # Lane M.1 scoreboard tier: consulted when the defaults entry is a 0-0
    # seed (a placeholder that must not short-circuit) - never when there
    # is no defaults entry at all (that path stays byte-identical legacy).
    if defaults_is_seed:
        data = scoreboard if scoreboard is not None else load_scoreboard()
        if data:
            ranked_sb = _scoreboard_rank(data, kind, assignee=assignee)
            if ranked_sb:
                best = ranked_sb[0]
                runner_up = ranked_sb[1] if len(ranked_sb) > 1 else None
                trip_probe = (
                    kind != "ops"
                    and runner_up is not None
                    and probe_every_n > 0
                    and cards_of_kind_created_so_far > 0
                    and (cards_of_kind_created_so_far % probe_every_n == 0)
                )
                if trip_probe and runner_up is not None:
                    return ChooseResult(
                        runner_up["provider"], runner_up["model"],
                        reason=_scoreboard_reason(kind, runner_up,
                                                  data.get("window_days")),
                        probe=True,
                        runner_up=(best["provider"], best["model"]),
                    )
                return ChooseResult(
                    best["provider"], best["model"],
                    reason=_scoreboard_reason(kind, best, data.get("window_days")),
                    runner_up=(runner_up["provider"], runner_up["model"])
                    if runner_up else None,
                )

    if ledger is None:
        ledger = build_ledger(conn=conn)
    ranked = _rank_for_kind(ledger, kind)
    if not ranked:
        prov, model = _STATIC_ROLES[kind]
        return ChooseResult(prov, model, reason="static-no-data")
    best = ranked[0]
    runner_up = ranked[1] if len(ranked) > 1 else None
    trip_probe = (
        kind != "ops"
        and runner_up is not None
        and probe_every_n > 0
        and cards_of_kind_created_so_far > 0
        and (cards_of_kind_created_so_far % probe_every_n == 0)
    )
    if trip_probe and runner_up:
        return ChooseResult(
            runner_up["provider"], runner_up["model"], reason="probe", probe=True,
            runner_up=(best["provider"], best["model"]),
        )
    return ChooseResult(
        best["provider"], best["model"], reason="ledger",
        runner_up=(runner_up["provider"], runner_up["model"]) if runner_up else None,
    )


# --- Create-path wiring (Lane M.1) -------------------------------------------

def choose_for_new_card(
    conn, body: Optional[str], assignee: Optional[str],
) -> Optional[ChooseResult]:
    """Chooser wiring shared by every card-create entry point.

    Returns None when the caller passed an explicit model (nothing to do),
    when the body declares no ``kind:`` line (nothing to rank), or when the
    chooser itself fails (create must never die on routing).  Otherwise the
    caller stamps ``ChooseResult.provider/model`` into the new card's
    model_override/provider_override and appends ``chooser: <reason>`` to
    its event log.
    """
    try:
        kind = extract_kind(body)
        if kind == "unknown":
            return None
        created = _count_cards_of_kind(conn, kind)
        return choose_agent(kind, cards_of_kind_created_so_far=created,
                            conn=conn, assignee=assignee)
    except Exception:
        return None


def _log_chooser_event(conn, task_id: str, result: "ChooseResult") -> None:
    """Append ``chooser: <reason>`` to the card's event log at create."""
    try:
        with kb.write_txn(conn):
            conn.execute(
                "INSERT INTO task_events (task_id, run_id, kind, payload, created_at) "
                "VALUES (?, NULL, 'chooser', ?, ?)",
                (task_id, kb._json_or_null({"reason": result.reason,
                                            "provider": result.provider,
                                            "model": result.model,
                                            "probe": result.probe}),
                 int(time.time())),
            )
    except Exception:
        pass  # never fail a create over a log line


# --- Rendering ---------------------------------------------------------------

def render_ledger_table(ledger: dict[str, Any]) -> str:
    rows = ledger["rows"]
    if not rows:
        return (
            f"(no ledger data in the last {ledger['window_days']} days; "
            "chooser falls back to static role routing)"
        )
    cols = ("kind", "provider", "model", "attempts", "completed", "review_pass",
            "review_fail", "review_pass_rate", "blocked_needs_input",
            "median_duration_s", "tokens_in", "tokens_out", "cost_usd")
    headers = {c: c for c in cols}

    def fmt(v):
        if v is None:
            return "-"
        if isinstance(v, float):
            return f"{v:.2f}"
        return str(v)
    widths = {c: max(len(headers[c]), *(len(fmt(r.get(c))) for r in rows)) for c in cols}
    line = "  ".join(headers[c].ljust(widths[c]) for c in cols)
    sep = "-" * len(line)
    out = [
        f"Agent performance ledger  (window: {ledger['window_days']}d, "
        f"generated_at={ledger['generated_at']}, tasks={ledger['totals']['tasks_considered']}, "
        f"runs={ledger['totals']['runs_considered']})",
        "",
        line,
        sep,
    ]
    for r in rows:
        out.append("  ".join(fmt(r.get(c)).ljust(widths[c]) for c in cols))
    return "\n".join(out)


def cmd_ledger(args) -> int:
    """``hermes kanban ledger`` handler."""
    with kbc.connect_closing() as conn:
        data = build_ledger(conn, window_days=int(getattr(args, "window_days", None)
                                                  or LEDGER_WINDOW_DAYS))
    if getattr(args, "json", False):
        print(json.dumps(data, ensure_ascii=True))
    else:
        print(render_ledger_table(data))
    return 0


__all__ = [
    "LEDGER_WINDOW_DAYS", "DEFAULT_PROBE_EVERY_N",
    "extract_kind", "build_ledger", "render_ledger_table",
    "choose_agent", "ChooseResult", "cmd_ledger",
    "load_defaults", "load_scoreboard",
]
